Add recycle port HLD.
Azure/SONiC pull request #742
Opened 2021-01-26 01:39 UTC by ysmanman

2021-01-27 17:35 UTC, eswaranb reviewed
1. Support host if for recycle port?
2. Update show command to support the recycle port.
3. Inband port can be configured to be Recirc0

2021-01-27 17:36 UTC, eswaranb commented on doc/voq/recycle_port.md
> +Recirc0       221                       Recirc0/0    5      Rec        400000
Inband0       221                      Inband0    5      Rec        400000
Recirc0       222                      Recirc0    6      Rec        400000

2021-01-27 17:52 UTC, ysmanman commented on doc/voq/recycle_port.md
> +Recirc1       222                       Recirc0/1    6      Rec        400000
Add a new role Inb for inband.

2021-01-27 17:53 UTC, ysmanman commented on doc/voq/recycle_port.md
> +Recirc0       221                       Recirc0/0    5      Rec        400000
Rename Recirc0 -> Ethernet-Recirc0.

2021-02-03 17:22 UTC, anshuv-mfst commented
@rlhui , @arlakshm - Could you please review the PR, thanks.  
@skeesara-nokia - could you please review the PR, thanks.

2021-03-03 06:38 UTC, rlhui reviewed
How to create a recycle port with SAI?

2021-03-03 17:21 UTC, ysmanman commented
> How to create a recycle port with SAI?

This should be similar to front panel ports. Recycle ports are defined in port_config.ini, and are populated in APP_DB port table. portsorch retrieves ports list, including recycle ports, from SAI in initialization, and initialize recycle ports just like other front panel ports in doTask.

2021-03-03 18:38 UTC, rlhui commented
> > How to create a recycle port with SAI?
> 
> This should be similar to front panel ports. Recycle ports are defined in port_config.ini, and are populated in APP_DB port table. portsorch retrieves ports list, including recycle ports, from SAI in initialization, and initialize recycle ports just like other front panel ports in doTask.

how to convey to ASIC SAI implementation that this is not an actual front-panel port, but to add 1 or 2 recycle ports?

2021-03-03 18:55 UTC, ysmanman commented
> > > How to create a recycle port with SAI?
> > 
> > 
> > This should be similar to front panel ports. Recycle ports are defined in port_config.ini, and are populated in APP_DB port table. portsorch retrieves ports list, including recycle ports, from SAI in initialization, and initialize recycle ports just like other front panel ports in doTask.
> 
> how to convey to ASIC SAI implementation that this is not an actual front-panel port, but to add 1 or 2 recycle ports?

If a SAI implementation needs to differentiate recycle port from recycle ports, it can encode a sub port type in the pid of recycle port. But this is transparent to orchagent since all orchagent needs is just a pid for recycle port.

2021-03-07 17:55 UTC, abdosi commented
Some Question on QoS w.r.t Recycle Port:-

What about the Queue of recycle port ? Do we will have Queue stats for recycle port ?  What will be behaviour of PFC and recycle port ? Can this port get back pressure for PFC queue 3 and 4 ?

2021-03-07 17:55 UTC, abdosi requested changes
Some questions on Qos.

2021-03-09 15:24 UTC, skeesara-nokia commented
> 
> 
> Some Question on QoS w.r.t Recycle Port:-
> 
> What about the Queue of recycle port ? Do we will have Queue stats for recycle port ? What will be behaviour of PFC and recycle port ? Can this port get back pressure for PFC queue 3 and 4 ?



> 
> 
> Some Question on QoS w.r.t Recycle Port:-
> 
> What about the Queue of recycle port ? Do we will have Queue stats for recycle port ? What will be behaviour of PFC and recycle port ? Can this port get back pressure for PFC queue 3 and 4 ?

Recycle port is expected to have queue statistics like any other port.
The back pressure part may be implementation dependent. Expect more clarity on that once the Recycle port proposal is reviewed in the SAI forum.

2021-03-09 15:26 UTC, skeesara-nokia commented
> 
> 
> Some questions on Qos.

QOS for the recycle port in general works similar any other port. It will support queues, mappings, remarking etc.

2021-03-09 21:12 UTC, ysmanman commented on doc/voq/recycle_port.md
> +Ethernet-Rec1       222                       Recirc0/1    6      Inb        400000
Sounds good. Fixed.

2021-03-09 22:07 UTC, skeesara-nokia approved these changes

2021-03-10 16:56 UTC, rlhui commented
> _No description provided._



> > Some Question on QoS w.r.t Recycle Port:-
> > What about the Queue of recycle port ? Do we will have Queue stats for recycle port ? What will be behaviour of PFC and recycle port ? Can this port get back pressure for PFC queue 3 and 4 ?
> 
> > Some Question on QoS w.r.t Recycle Port:-
> > What about the Queue of recycle port ? Do we will have Queue stats for recycle port ? What will be behaviour of PFC and recycle port ? Can this port get back pressure for PFC queue 3 and 4 ?
> 
> Recycle port is expected to have queue statistics like any other port.
> The back pressure part may be implementation dependent. Expect more clarity on that once the Recycle port proposal is reviewed in the SAI forum.

I would like to request that we add to the doc the usage of the SAI recycle port API - the current raised idea is to add a subport type for the recycle port.  How will this be used by the sonic applications/users?

2021-03-17 01:15 UTC, ysmanman commented
> > _No description provided._
> 
> > > Some Question on QoS w.r.t Recycle Port:-
> > > What about the Queue of recycle port ? Do we will have Queue stats for recycle port ? What will be behaviour of PFC and recycle port ? Can this port get back pressure for PFC queue 3 and 4 ?
> > 
> > 
> > > Some Question on QoS w.r.t Recycle Port:-
> > > What about the Queue of recycle port ? Do we will have Queue stats for recycle port ? What will be behaviour of PFC and recycle port ? Can this port get back pressure for PFC queue 3 and 4 ?
> > 
> > 
> > Recycle port is expected to have queue statistics like any other port.
> > The back pressure part may be implementation dependent. Expect more clarity on that once the Recycle port proposal is reviewed in the SAI forum.
> 
> I would like to request that we add to the doc the usage of the SAI recycle port API - the current raised idea is to add a subport type for the recycle port. How will this be used by the sonic applications/users?

The HLD proposes to use recycle port in a way that’s independent of the SAI recycele port API. In this proposal, SONiC application/users shouldn’t really care about if a subport type is defined for recycle port or not. What we proposed in the HLD is to use port role to identify recycle ports in SONiC and its applications. Detailedly, we define recycle ports by setting the specific port roles along with their lanes in port_config.ini. With lanes and roles from port_config.ini, portsorch should be able to initialize recycle ports and also uncover their pid returned by SAI. SONiC applications that need recycle ports, like Everflow, should simply request the pid of recycle port from portsorch. It’s not clear to me why we have to define a subport type for recycle port. Did I get your comment correct?

2021-03-17 01:29 UTC, ysmanman commented
> > > > > How to create a recycle port with SAI?
> > > > 
> > > > 
> > > > This should be similar to front panel ports. Recycle ports are defined in port_config.ini, and are populated in APP_DB port table. portsorch retrieves ports list, including recycle ports, from SAI in initialization, and initialize recycle ports just like other front panel ports in doTask.
> > > 
> > > 
> > > how to convey to ASIC SAI implementation that this is not an actual front-panel port, but to add 1 or 2 recycle ports?
> > 
> > 
> > If a SAI implementation needs to differentiate recycle port from recycle ports, it can encode a sub port type in the pid of recycle port. But this is transparent to orchagent since all orchagent needs is just a pid for recycle port.
> 
> > > > > How to create a recycle port with SAI?
> > > > 
> > > > 
> > > > This should be similar to front panel ports. Recycle ports are defined in port_config.ini, and are populated in APP_DB port table. portsorch retrieves ports list, including recycle ports, from SAI in initialization, and initialize recycle ports just like other front panel ports in doTask.
> > > 
> > > 
> > > how to convey to ASIC SAI implementation that this is not an actual front-panel port, but to add 1 or 2 recycle ports?
> > 
> > 
> > If a SAI implementation needs to differentiate recycle port from recycle ports, it can encode a sub port type in the pid of recycle port. But this is transparent to orchagent since all orchagent needs is just a pid for recycle port.
> 
> Would we please add to the doc on this. Thanks.

As I replied to another comment,  this seems not relevant to the proposal in the HLD.

2021-04-07 04:55 UTC, ysmanman commented
> Some questions on Qos.

This comment had been addressed already. Copy the reply again to update review status:

QOS for the recycle port in general works similar any other port. It will support queues, mappings, remarking etc.

2021-05-19 00:17 UTC, abdosi approved these changes

2021-06-02 02:00 UTC, merged