Update extension-to-physical-entity-mib.md to add a description about the Entity sensor MIB extension
Azure/SONiC pull request #766
Opened 2021-03-27 01:54 UTC by keboliu

Extend the Entity sensor MIB to include more sensors.
currently, Entity sensor MIB only include the SFP DOM sensors, in this extension, will add below sensors:
1. the PSU voltage, current, power, temp
2. Chassis fan speed, PSU fan speed
3. Thermal sensors avalaible on the switch(ASIC, CPU, Ambt, etc.)

2021-03-29 18:24 UTC, jleveque requested changes

2021-03-29 18:24 UTC, jleveque commented on doc/snmp/extension-to-physical-entity-mib.md
> +Thermal sensors besides the Transceiver embeded thermal sensors which avalaible in the STATE_DB will all be added to the Entity Sensor MIB support.
Typo: s/embeded/embedded/

2021-03-29 18:24 UTC, jleveque commented on doc/snmp/extension-to-physical-entity-mib.md
> +All new added MIB will be initilized and updated based on the data stored in the STATE_DB, to be more specific:
Typo: s/initilized/initialized/

2021-03-31 17:38 UTC, jleveque commented
Looks good to me. @qiluo-msft to review from an SNMP perspective.

2021-04-01 08:27 UTC, keboliu commented
Hi, @jleveque would you please check my update regarding your comments?

2021-04-01 16:27 UTC, jleveque approved these changes

2021-04-01 17:23 UTC, merged